# Generated by Django 5.1.5 on 2025-01-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='assignment',
            new_name='assignments',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='day',
            new_name='selected_day',
        ),
    ]
