# Generated by Django 5.1.5 on 2025-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_assignment_todo_assignments_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('selected_day', 'assignments'), name='unique_constraint'),
        ),
    ]
